### ISSUE TITLE
Setting options through Tweakpane

### ISSUE THREAD

**Issue by kingsushi001** [jerosoler/waveform-path#2]
Hi

I've been learning JS the past few days. And for the life of me I can't figure out how to use waveform-path with [Tweakpane](https://cocopon.github.io/tweakpane/).
I have no idea how to actually update the waveform with values from [Tweakpane](https://cocopon.github.io/tweakpane/).

This is my script:
```
import { getAudioData, linearPath, polarPath } from '../node_modules/waveform-path/dist/waveform-path.min.js';
const Tweakpane = require('tweakpane');

const params = {
    Samples: 100,
    Color: '#000000',
}

async function AudioPath(file) {
    const audioData = await getAudioData(file);

    const wave = linearPath(audioData,{ samples: params.Samples,  type: 'mirror', width: 1500, height: 500,
    paths: [ 
        {d:'V', sy: 0, x:50, ey:100 }
    ] });

    document.querySelector("#waveform path").setAttribute('d', wave);
    document.querySelector("#waveform path").setAttribute('stroke', params.Color);
}

AudioPath("song.mp3");

const createPane = () => {
    const pane = new Tweakpane.Pane();
    let folder;

    folder = pane.addFolder({ title: 'Settings'});
    folder.addInput(params, 'Samples', { min: 50, max: 400, step: 1 });
    folder.addInput(params, 'Color');
}

createPane();
```
Am I missing something somewhere?
Any help would be greatly appreciated .

**Comment by jerosoler** [comment]
Hello,

You are not listening to the events. To reload the waveform.

Here an example.

### HTML
```html
<svg id="waveform" height="140px" width="800px" >
  <path />
</svg>
```

### Javascript
```javascript
import { getAudioData, linearPath, polarPath } from 'https://cdn.skypack.dev/waveform-path';

import Tweakpane from 'https://cdn.skypack.dev/tweakpane';

const params = {
    Samples: 100,
    Color: '#000000',
}

async function AudioPath(file) {
    const audioData = await getAudioData(file);

    const wave = linearPath(audioData,{ samples: params.Samples,  type: 'mirror', width: 1500, height: 500,
    paths: [ 
        {d:'V', sy: 0, x:50, ey:100 }
    ] });

    document.querySelector("#waveform path").setAttribute('d', wave);
    document.querySelector("#waveform path").setAttribute('stroke', params.Color);
}

AudioPath("https://jerosoler.github.io/waveform-path/hello_world.ogg");
 
const createPane = () => {
    const pane = new Tweakpane.Pane();
    let folder;

    folder = pane.addFolder({ title: 'Settings'});
    const samples = folder.addInput(params, 'Samples', { min: 50, max: 400, step: 1 });
    const color =  folder.addInput(params, 'Color');
    samples.on('change', function(ev) {
      params.Samples = ev.value;
      AudioPath("https://jerosoler.github.io/waveform-path/hello_world.ogg");
    })
    color.on('change', function(ev) {
      params.Color = ev.value;
      AudioPath("https://jerosoler.github.io/waveform-path/hello_world.ogg");
    })
}

createPane();
```

Link example:
[Demo](https://codi.link/PHN2ZyBpZD0id2F2ZWZvcm0iIGhlaWdodD0iMTQwcHgiIHdpZHRoPSI4MDBweCIgPgogIDxwYXRoIC8+Cjwvc3ZnPg==%7C%7CaW1wb3J0IHsgZ2V0QXVkaW9EYXRhLCBsaW5lYXJQYXRoLCBwb2xhclBhdGggfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi93YXZlZm9ybS1wYXRoJzsKCmltcG9ydCBUd2Vha3BhbmUgZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvdHdlYWtwYW5lJzsKCmNvbnN0IHBhcmFtcyA9IHsKICAgIFNhbXBsZXM6IDEwMCwKICAgIENvbG9yOiAnIzAwMDAwMCcsCn0KCmFzeW5jIGZ1bmN0aW9uIEF1ZGlvUGF0aChmaWxlKSB7CiAgICBjb25zdCBhdWRpb0RhdGEgPSBhd2FpdCBnZXRBdWRpb0RhdGEoZmlsZSk7CgogICAgY29uc3Qgd2F2ZSA9IGxpbmVhclBhdGgoYXVkaW9EYXRhLHsgc2FtcGxlczogcGFyYW1zLlNhbXBsZXMsICB0eXBlOiAnbWlycm9yJywgd2lkdGg6IDE1MDAsIGhlaWdodDogNTAwLAogICAgcGF0aHM6IFsgCiAgICAgICAge2Q6J1YnLCBzeTogMCwgeDo1MCwgZXk6MTAwIH0KICAgIF0gfSk7CgogICAgZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiI3dhdmVmb3JtIHBhdGgiKS5zZXRBdHRyaWJ1dGUoJ2QnLCB3YXZlKTsKICAgIGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3IoIiN3YXZlZm9ybSBwYXRoIikuc2V0QXR0cmlidXRlKCdzdHJva2UnLCBwYXJhbXMuQ29sb3IpOwp9CgpBdWRpb1BhdGgoImh0dHBzOi8vamVyb3NvbGVyLmdpdGh1Yi5pby93YXZlZm9ybS1wYXRoL2hlbGxvX3dvcmxkLm9nZyIpOwogCmNvbnN0IGNyZWF0ZVBhbmUgPSAoKSA9PiB7CiAgICBjb25zdCBwYW5lID0gbmV3IFR3ZWFrcGFuZS5QYW5lKCk7CiAgICBsZXQgZm9sZGVyOwoKICAgIGZvbGRlciA9IHBhbmUuYWRkRm9sZGVyKHsgdGl0bGU6ICdTZXR0aW5ncyd9KTsKICAgIGNvbnN0IHNhbXBsZXMgPSBmb2xkZXIuYWRkSW5wdXQocGFyYW1zLCAnU2FtcGxlcycsIHsgbWluOiA1MCwgbWF4OiA0MDAsIHN0ZXA6IDEgfSk7CiAgICBjb25zdCBjb2xvciA9ICBmb2xkZXIuYWRkSW5wdXQocGFyYW1zLCAnQ29sb3InKTsKICAgIHNhbXBsZXMub24oJ2NoYW5nZScsIGZ1bmN0aW9uKGV2KSB7CiAgICAgIHBhcmFtcy5TYW1wbGVzID0gZXYudmFsdWU7CiAgICAgIEF1ZGlvUGF0aCgiaHR0cHM6Ly9qZXJvc29sZXIuZ2l0aHViLmlvL3dhdmVmb3JtLXBhdGgvaGVsbG9fd29ybGQub2dnIik7CiAgICB9KQogICAgY29sb3Iub24oJ2NoYW5nZScsIGZ1bmN0aW9uKGV2KSB7CiAgICAgIHBhcmFtcy5Db2xvciA9IGV2LnZhbHVlOwogICAgICBBdWRpb1BhdGgoImh0dHBzOi8vamVyb3NvbGVyLmdpdGh1Yi5pby93YXZlZm9ybS1wYXRoL2hlbGxvX3dvcmxkLm9nZyIpOwogICAgfSkKfQoKY3JlYXRlUGFuZSgpOwoK)

**Comment by kingsushi001** [comment]
Thank you so much! It's working great.
