### ISSUE TITLE
Samples Clarification

### ISSUE THREAD

**Issue by asktimfisher** [jerosoler/waveform-path#3]
You mention "samples" is "Length of the data" but I'm not sure what that means. Your examples list all as 100 but the length of the data would be variable, it wouldn't always be 100.

Is "samples" instead "samples" in other audio contexts, as in the number of sample rate, as in the number of samples to take per second?

**Comment by jerosoler** [comment]
Hi @asktimfisher 

I don't know if the term is correct.

The library is based on this Css Tricks Post: https://css-tricks.com/making-an-audio-waveform-visualizer-with-vanilla-javascript/

Basically it would be the number of lines to display.

Examples with same file:

Example With 20 samples:
![image](https://github.com/jerosoler/waveform-path/assets/30957047/bb70b087-426f-455c-93d9-c14893dcea46)


Example With 100 samples:
![image](https://github.com/jerosoler/waveform-path/assets/30957047/0e9b3b30-3d8c-4bbf-a59a-1797895036f9)


Example with 300 samples:
![image](https://github.com/jerosoler/waveform-path/assets/30957047/6116e715-95dd-4e9e-a500-7856ec22b248)


Demo: 
https://codi.link/PHN2ZyBpZD0id2F2ZWZvcm0iIGhlaWdodD0iMTQwcHgiIHdpZHRoPSI4MDBweCIgPgogIDxwYXRoIC8+Cjwvc3ZnPg==%7C%7CaW1wb3J0IHsgZ2V0QXVkaW9EYXRhLCBsaW5lYXJQYXRoLCBwb2xhclBhdGggfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi93YXZlZm9ybS1wYXRoJzsKCmltcG9ydCBUd2Vha3BhbmUgZnJvbSAnaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXYvdHdlYWtwYW5lJzsKCmNvbnN0IHBhcmFtcyA9IHsKICAgIFNhbXBsZXM6IDMwMCwKICAgIENvbG9yOiAnIzAwMDAwMCcsCn0KCmFzeW5jIGZ1bmN0aW9uIEF1ZGlvUGF0aChmaWxlKSB7CiAgICBjb25zdCBhdWRpb0RhdGEgPSBhd2FpdCBnZXRBdWRpb0RhdGEoZmlsZSk7CgogICAgY29uc3Qgd2F2ZSA9IGxpbmVhclBhdGgoYXVkaW9EYXRhLHsgc2FtcGxlczogcGFyYW1zLlNhbXBsZXMsICB0eXBlOiAnbWlycm9yJywgd2lkdGg6IDgwMCwgaGVpZ2h0OiAxNDAsCiAgICBwYXRoczogWyAKICAgICAgICB7ZDonVicsIHN5OiAwLCB4OjUwLCBleToxMDAgfQogICAgXSB9KTsKCiAgICBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCIjd2F2ZWZvcm0gcGF0aCIpLnNldEF0dHJpYnV0ZSgnZCcsIHdhdmUpOwogICAgZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiI3dhdmVmb3JtIHBhdGgiKS5zZXRBdHRyaWJ1dGUoJ3N0cm9rZScsIHBhcmFtcy5Db2xvcik7Cn0KCkF1ZGlvUGF0aCgiaHR0cHM6Ly9qZXJvc29sZXIuZ2l0aHViLmlvL3dhdmVmb3JtLXBhdGgvaGVsbG9fd29ybGQub2dnIik7CiAKY29uc3QgY3JlYXRlUGFuZSA9ICgpID0+IHsKICAgIGNvbnN0IHBhbmUgPSBuZXcgVHdlYWtwYW5lLlBhbmUoKTsKICAgIGxldCBmb2xkZXI7CgogICAgZm9sZGVyID0gcGFuZS5hZGRGb2xkZXIoeyB0aXRsZTogJ1NldHRpbmdzJ30pOwogICAgY29uc3Qgc2FtcGxlcyA9IGZvbGRlci5hZGRJbnB1dChwYXJhbXMsICdTYW1wbGVzJywgeyBtaW46IDUwLCBtYXg6IDQwMCwgc3RlcDogMSB9KTsKICAgIGNvbnN0IGNvbG9yID0gIGZvbGRlci5hZGRJbnB1dChwYXJhbXMsICdDb2xvcicpOwogICAgc2FtcGxlcy5vbignY2hhbmdlJywgZnVuY3Rpb24oZXYpIHsKICAgICAgcGFyYW1zLlNhbXBsZXMgPSBldi52YWx1ZTsKICAgICAgQXVkaW9QYXRoKCJodHRwczovL2plcm9zb2xlci5naXRodWIuaW8vd2F2ZWZvcm0tcGF0aC9oZWxsb193b3JsZC5vZ2ciKTsKICAgIH0pCiAgICBjb2xvci5vbignY2hhbmdlJywgZnVuY3Rpb24oZXYpIHsKICAgICAgcGFyYW1zLkNvbG9yID0gZXYudmFsdWU7CiAgICAgIEF1ZGlvUGF0aCgiaHR0cHM6Ly9qZXJvc29sZXIuZ2l0aHViLmlvL3dhdmVmb3JtLXBhdGgvaGVsbG9fd29ybGQub2dnIik7CiAgICB9KQp9CgpjcmVhdGVQYW5lKCk7Cgo=

**Comment by asktimfisher** [comment]
Perfect! Yeah, I'm not sure either if it's the right word but this answers my question perfectly. Thanks!
