### ISSUE TITLE
Wave form for the whole audio duration ?

### ISSUE THREAD

**Issue by hugolpz** [jerosoler/waveform-path#7]
Hello @jerosoler ,

I see on your demo that your library represent the audio waves at a time T.

Can your library display the whole duration's overall waveform ? as this code do : https://codepen.io/hugolpz/pen/eYoKaBj 

If so that case I would like to use your library, the SVG are a plus+ :3

**Comment by jerosoler** [comment]
Hi @hugolpz 

Yes, it allows you to show the entire duration. What is calculated in the browser and in some cases it could take time.

You can also see here a webcomponent created with this library.

Demo: https://jerosoler.github.io/wave-audio-path-player/

And repo: https://github.com/jerosoler/wave-audio-path-player

**Comment by jerosoler** [comment]
Same file in your example:

View in link:

https://codi.link/PHN2ZyBpZD0iZXhhbXBsZTEwIiBoZWlnaHQ9IjE0MHB4IiB3aWR0aD0iODAwcHgiPgogICAgICAgICAgICA8cGF0aCBkPSIiIHN0eWxlPSJmaWxsOm5vbmU7IHN0cm9rZS13aWR0aDogMzsgc3Ryb2tlOnJlZCIgPgogICAgICAgICAgICA8L3BhdGg+Cjwvc3ZnPg==%7C%7CaW1wb3J0IHsgZ2V0QXVkaW9EYXRhLCBsaW5lYXJQYXRoLCBwb2xhclBhdGggfSBmcm9tICdodHRwczovL2Nkbi5za3lwYWNrLmRldi93YXZlZm9ybS1wYXRoJzsKCmFzeW5jIGZ1bmN0aW9uIEF1ZGlvUGF0aChmaWxlKSB7CiAgICBjb25zdCBhdWRpb0RhdGEgPSBhd2FpdCBnZXRBdWRpb0RhdGEoZmlsZSk7CgogICAgY29uc3QgZXhhbXBsZTEwID0gbGluZWFyUGF0aChhdWRpb0RhdGEseyAKICAgICAgICBzYW1wbGVzOiAxMDAsIHR5cGU6ICdzdGVwcycsIHRvcDogMjAKICAgIH0pOwogICAgZG9jdW1lbnQucXVlcnlTZWxlY3RvcigiI2V4YW1wbGUxMCBwYXRoIikuc2V0QXR0cmlidXRlKCdkJywgZXhhbXBsZTEwKTsKfQpBdWRpb1BhdGgoImh0dHBzOi8vdXBsb2FkLndpa2ltZWRpYS5vcmcvd2lraXBlZGlhL2NvbW1vbnMvdHJhbnNjb2RlZC8wLzBiL0xMLVExNDE4NV8lMjhvY2klMjktVW5pdiVDMyVCMmM2NC1Mb2JpJUMzJUE4cl9kZV9IYXV0Lndhdi9MTC1RMTQxODVfJTI4b2NpJTI5LVVuaXYlQzMlQjJjNjQtTG9iaSVDMyVBOHJfZGVfSGF1dC53YXYubXAzIik7CiAKIAoKCg==

**Comment by hugolpz** [comment]
@jerosoler thank you. I tinkered your code and finaly came up with the three following demo : 
- Minimal static audio list : https://jsfiddle.net/hugolpz/vre7hgto/2/
- Wikidata driven audio list: https://jsfiddle.net/hugolpz/vre7hgto/6/
- Map : https://hugolpz.github.io/NamesOfTheLand/ ([gh](https://github.com/hugolpz/NamesOfTheLand))

I'm working on open licence Occitan whistle project, having the sound wave is a plus ! 😉 

![image](https://github.com/jerosoler/waveform-path/assets/1420189/01ea7d90-0167-4e10-bf8b-3f09fb67e832)
![image](https://github.com/jerosoler/waveform-path/assets/1420189/bf4704a5-0c38-466f-b1e6-8c8aa11e737a)

We can close this issue. Thank you again !

**Comment by jerosoler** [comment]
Wow! nice project! @hugolpz  And beautiful region Occitanie ❤️.

Good luck with your project.

Thanks for using the library! ;)
If you feel like it, you can make a donation to continue creating projects! Or mark with a star.
